#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'ARGB.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.6.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 6
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:803
#include "global.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'ARGB'
// Defined at ARGB.kl:19:1

struct ARGB
{
  typedef ARGB &Result;
  typedef ARGB const &INParam;
  typedef ARGB &IOParam;
  typedef ARGB &OUTParam;
  
  ::Fabric::EDK::KL::UInt8 a;
  ::Fabric::EDK::KL::UInt8 r;
  ::Fabric::EDK::KL::UInt8 g;
  ::Fabric::EDK::KL::UInt8 b;
};

inline void Traits<ARGB>::ConstructEmpty( ARGB &val )
{
  Traits< ::Fabric::EDK::KL::UInt8 >::ConstructEmpty( val.a );
  Traits< ::Fabric::EDK::KL::UInt8 >::ConstructEmpty( val.r );
  Traits< ::Fabric::EDK::KL::UInt8 >::ConstructEmpty( val.g );
  Traits< ::Fabric::EDK::KL::UInt8 >::ConstructEmpty( val.b );
}
inline void Traits<ARGB>::ConstructCopy( ARGB &lhs, ARGB const &rhs )
{
  Traits< ::Fabric::EDK::KL::UInt8 >::ConstructCopy( lhs.a, rhs.a );
  Traits< ::Fabric::EDK::KL::UInt8 >::ConstructCopy( lhs.r, rhs.r );
  Traits< ::Fabric::EDK::KL::UInt8 >::ConstructCopy( lhs.g, rhs.g );
  Traits< ::Fabric::EDK::KL::UInt8 >::ConstructCopy( lhs.b, rhs.b );
}
inline void Traits<ARGB>::AssignCopy( ARGB &lhs, ARGB const &rhs )
{
  Traits< ::Fabric::EDK::KL::UInt8 >::AssignCopy( lhs.a, rhs.a );
  Traits< ::Fabric::EDK::KL::UInt8 >::AssignCopy( lhs.r, rhs.r );
  Traits< ::Fabric::EDK::KL::UInt8 >::AssignCopy( lhs.g, rhs.g );
  Traits< ::Fabric::EDK::KL::UInt8 >::AssignCopy( lhs.b, rhs.b );
}
inline void Traits<ARGB>::Destruct( ARGB &val )
{
  Traits< ::Fabric::EDK::KL::UInt8 >::Destruct( val.b );
  Traits< ::Fabric::EDK::KL::UInt8 >::Destruct( val.g );
  Traits< ::Fabric::EDK::KL::UInt8 >::Destruct( val.r );
  Traits< ::Fabric::EDK::KL::UInt8 >::Destruct( val.a );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


