#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Box3.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.5.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 5
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:803
#include "global.h"
// Core\Clients\CAPI\KL2EDK.cpp:855
#include "Vec3.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Box3'
// Defined at Box3.kl:22:1

struct Box3
{
  typedef Box3 &Result;
  typedef Box3 const &INParam;
  typedef Box3 &IOParam;
  typedef Box3 &OUTParam;
  
  ::Fabric::EDK::KL::Vec3 min;
  ::Fabric::EDK::KL::Vec3 max;
};

inline void Traits<Box3>::ConstructEmpty( Box3 &val )
{
  Traits< ::Fabric::EDK::KL::Vec3 >::ConstructEmpty( val.min );
  Traits< ::Fabric::EDK::KL::Vec3 >::ConstructEmpty( val.max );
}
inline void Traits<Box3>::ConstructCopy( Box3 &lhs, Box3 const &rhs )
{
  Traits< ::Fabric::EDK::KL::Vec3 >::ConstructCopy( lhs.min, rhs.min );
  Traits< ::Fabric::EDK::KL::Vec3 >::ConstructCopy( lhs.max, rhs.max );
}
inline void Traits<Box3>::AssignCopy( Box3 &lhs, Box3 const &rhs )
{
  Traits< ::Fabric::EDK::KL::Vec3 >::AssignCopy( lhs.min, rhs.min );
  Traits< ::Fabric::EDK::KL::Vec3 >::AssignCopy( lhs.max, rhs.max );
}
inline void Traits<Box3>::Destruct( Box3 &val )
{
  Traits< ::Fabric::EDK::KL::Vec3 >::Destruct( val.max );
  Traits< ::Fabric::EDK::KL::Vec3 >::Destruct( val.min );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


