#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Mat22_cd.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.6.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 6
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:803
#include "global.h"
// Core\Clients\CAPI\KL2EDK.cpp:855
#include "Vec2_cd.h"
// Core\Clients\CAPI\KL2EDK.cpp:855
#include "Complex_d.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Mat22_cd'
// Defined at Mat22_cd.kl:21:1

struct Mat22_cd
{
  typedef Mat22_cd &Result;
  typedef Mat22_cd const &INParam;
  typedef Mat22_cd &IOParam;
  typedef Mat22_cd &OUTParam;
  
  ::Fabric::EDK::KL::Vec2_cd row0;
  ::Fabric::EDK::KL::Vec2_cd row1;
};

inline void Traits<Mat22_cd>::ConstructEmpty( Mat22_cd &val )
{
  Traits< ::Fabric::EDK::KL::Vec2_cd >::ConstructEmpty( val.row0 );
  Traits< ::Fabric::EDK::KL::Vec2_cd >::ConstructEmpty( val.row1 );
}
inline void Traits<Mat22_cd>::ConstructCopy( Mat22_cd &lhs, Mat22_cd const &rhs )
{
  Traits< ::Fabric::EDK::KL::Vec2_cd >::ConstructCopy( lhs.row0, rhs.row0 );
  Traits< ::Fabric::EDK::KL::Vec2_cd >::ConstructCopy( lhs.row1, rhs.row1 );
}
inline void Traits<Mat22_cd>::AssignCopy( Mat22_cd &lhs, Mat22_cd const &rhs )
{
  Traits< ::Fabric::EDK::KL::Vec2_cd >::AssignCopy( lhs.row0, rhs.row0 );
  Traits< ::Fabric::EDK::KL::Vec2_cd >::AssignCopy( lhs.row1, rhs.row1 );
}
inline void Traits<Mat22_cd>::Destruct( Mat22_cd &val )
{
  Traits< ::Fabric::EDK::KL::Vec2_cd >::Destruct( val.row1 );
  Traits< ::Fabric::EDK::KL::Vec2_cd >::Destruct( val.row0 );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


