#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Mat22_c.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.7.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 7
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:812
#include "global.h"
// Core\Clients\CAPI\KL2EDK.cpp:864
#include "Vec2_c.h"
// Core\Clients\CAPI\KL2EDK.cpp:864
#include "Complex.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Mat22_c'
// Defined at Mat22_c.kl:21:1

struct Mat22_c
{
  typedef Mat22_c &Result;
  typedef Mat22_c const &INParam;
  typedef Mat22_c &IOParam;
  typedef Mat22_c &OUTParam;
  
  ::Fabric::EDK::KL::Vec2_c row0;
  ::Fabric::EDK::KL::Vec2_c row1;
};

inline void Traits<Mat22_c>::ConstructEmpty( Mat22_c &val )
{
  Traits< ::Fabric::EDK::KL::Vec2_c >::ConstructEmpty( val.row0 );
  Traits< ::Fabric::EDK::KL::Vec2_c >::ConstructEmpty( val.row1 );
}
inline void Traits<Mat22_c>::ConstructCopy( Mat22_c &lhs, Mat22_c const &rhs )
{
  Traits< ::Fabric::EDK::KL::Vec2_c >::ConstructCopy( lhs.row0, rhs.row0 );
  Traits< ::Fabric::EDK::KL::Vec2_c >::ConstructCopy( lhs.row1, rhs.row1 );
}
inline void Traits<Mat22_c>::AssignCopy( Mat22_c &lhs, Mat22_c const &rhs )
{
  Traits< ::Fabric::EDK::KL::Vec2_c >::AssignCopy( lhs.row0, rhs.row0 );
  Traits< ::Fabric::EDK::KL::Vec2_c >::AssignCopy( lhs.row1, rhs.row1 );
}
inline void Traits<Mat22_c>::Destruct( Mat22_c &val )
{
  Traits< ::Fabric::EDK::KL::Vec2_c >::Destruct( val.row1 );
  Traits< ::Fabric::EDK::KL::Vec2_c >::Destruct( val.row0 );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


