#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Mat22_i.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.7.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 7
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:812
#include "global.h"
// Core\Clients\CAPI\KL2EDK.cpp:864
#include "Vec2_i.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Mat22_i'
// Defined at Mat22_i.kl:21:1

struct Mat22_i
{
  typedef Mat22_i &Result;
  typedef Mat22_i const &INParam;
  typedef Mat22_i &IOParam;
  typedef Mat22_i &OUTParam;
  
  ::Fabric::EDK::KL::Vec2_i row0;
  ::Fabric::EDK::KL::Vec2_i row1;
};

inline void Traits<Mat22_i>::ConstructEmpty( Mat22_i &val )
{
  Traits< ::Fabric::EDK::KL::Vec2_i >::ConstructEmpty( val.row0 );
  Traits< ::Fabric::EDK::KL::Vec2_i >::ConstructEmpty( val.row1 );
}
inline void Traits<Mat22_i>::ConstructCopy( Mat22_i &lhs, Mat22_i const &rhs )
{
  Traits< ::Fabric::EDK::KL::Vec2_i >::ConstructCopy( lhs.row0, rhs.row0 );
  Traits< ::Fabric::EDK::KL::Vec2_i >::ConstructCopy( lhs.row1, rhs.row1 );
}
inline void Traits<Mat22_i>::AssignCopy( Mat22_i &lhs, Mat22_i const &rhs )
{
  Traits< ::Fabric::EDK::KL::Vec2_i >::AssignCopy( lhs.row0, rhs.row0 );
  Traits< ::Fabric::EDK::KL::Vec2_i >::AssignCopy( lhs.row1, rhs.row1 );
}
inline void Traits<Mat22_i>::Destruct( Mat22_i &val )
{
  Traits< ::Fabric::EDK::KL::Vec2_i >::Destruct( val.row1 );
  Traits< ::Fabric::EDK::KL::Vec2_i >::Destruct( val.row0 );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


