#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Mat_cd.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.6.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 6
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:803
#include "global.h"
// Core\Clients\CAPI\KL2EDK.cpp:855
#include "Complex_d.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Mat_cd'
// Defined at Mat_cd.kl:19:1

struct Mat_cd
{
  typedef Mat_cd &Result;
  typedef Mat_cd const &INParam;
  typedef Mat_cd &IOParam;
  typedef Mat_cd &OUTParam;
  
  ::Fabric::EDK::KL::SInt32 rows;
  ::Fabric::EDK::KL::SInt32 cols;
  ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::Complex_d > vals;
};

inline void Traits<Mat_cd>::ConstructEmpty( Mat_cd &val )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructEmpty( val.rows );
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructEmpty( val.cols );
  Traits< ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::Complex_d > >::ConstructEmpty( val.vals );
}
inline void Traits<Mat_cd>::ConstructCopy( Mat_cd &lhs, Mat_cd const &rhs )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructCopy( lhs.rows, rhs.rows );
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructCopy( lhs.cols, rhs.cols );
  Traits< ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::Complex_d > >::ConstructCopy( lhs.vals, rhs.vals );
}
inline void Traits<Mat_cd>::AssignCopy( Mat_cd &lhs, Mat_cd const &rhs )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::AssignCopy( lhs.rows, rhs.rows );
  Traits< ::Fabric::EDK::KL::SInt32 >::AssignCopy( lhs.cols, rhs.cols );
  Traits< ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::Complex_d > >::AssignCopy( lhs.vals, rhs.vals );
}
inline void Traits<Mat_cd>::Destruct( Mat_cd &val )
{
  Traits< ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::Complex_d > >::Destruct( val.vals );
  Traits< ::Fabric::EDK::KL::SInt32 >::Destruct( val.cols );
  Traits< ::Fabric::EDK::KL::SInt32 >::Destruct( val.rows );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


