#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Mat_d.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.5.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 5
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:803
#include "global.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Mat_d'
// Defined at Mat_d.kl:19:1

struct Mat_d
{
  typedef Mat_d &Result;
  typedef Mat_d const &INParam;
  typedef Mat_d &IOParam;
  typedef Mat_d &OUTParam;
  
  ::Fabric::EDK::KL::SInt32 rows;
  ::Fabric::EDK::KL::SInt32 cols;
  ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::Float64 > vals;
};

inline void Traits<Mat_d>::ConstructEmpty( Mat_d &val )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructEmpty( val.rows );
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructEmpty( val.cols );
  Traits< ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::Float64 > >::ConstructEmpty( val.vals );
}
inline void Traits<Mat_d>::ConstructCopy( Mat_d &lhs, Mat_d const &rhs )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructCopy( lhs.rows, rhs.rows );
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructCopy( lhs.cols, rhs.cols );
  Traits< ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::Float64 > >::ConstructCopy( lhs.vals, rhs.vals );
}
inline void Traits<Mat_d>::AssignCopy( Mat_d &lhs, Mat_d const &rhs )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::AssignCopy( lhs.rows, rhs.rows );
  Traits< ::Fabric::EDK::KL::SInt32 >::AssignCopy( lhs.cols, rhs.cols );
  Traits< ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::Float64 > >::AssignCopy( lhs.vals, rhs.vals );
}
inline void Traits<Mat_d>::Destruct( Mat_d &val )
{
  Traits< ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::Float64 > >::Destruct( val.vals );
  Traits< ::Fabric::EDK::KL::SInt32 >::Destruct( val.cols );
  Traits< ::Fabric::EDK::KL::SInt32 >::Destruct( val.rows );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


