#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Mat_i.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.6.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 6
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:803
#include "global.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Mat_i'
// Defined at Mat_i.kl:19:1

struct Mat_i
{
  typedef Mat_i &Result;
  typedef Mat_i const &INParam;
  typedef Mat_i &IOParam;
  typedef Mat_i &OUTParam;
  
  ::Fabric::EDK::KL::SInt32 rows;
  ::Fabric::EDK::KL::SInt32 cols;
  ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::SInt32 > vals;
};

inline void Traits<Mat_i>::ConstructEmpty( Mat_i &val )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructEmpty( val.rows );
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructEmpty( val.cols );
  Traits< ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::SInt32 > >::ConstructEmpty( val.vals );
}
inline void Traits<Mat_i>::ConstructCopy( Mat_i &lhs, Mat_i const &rhs )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructCopy( lhs.rows, rhs.rows );
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructCopy( lhs.cols, rhs.cols );
  Traits< ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::SInt32 > >::ConstructCopy( lhs.vals, rhs.vals );
}
inline void Traits<Mat_i>::AssignCopy( Mat_i &lhs, Mat_i const &rhs )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::AssignCopy( lhs.rows, rhs.rows );
  Traits< ::Fabric::EDK::KL::SInt32 >::AssignCopy( lhs.cols, rhs.cols );
  Traits< ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::SInt32 > >::AssignCopy( lhs.vals, rhs.vals );
}
inline void Traits<Mat_i>::Destruct( Mat_i &val )
{
  Traits< ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::SInt32 > >::Destruct( val.vals );
  Traits< ::Fabric::EDK::KL::SInt32 >::Destruct( val.cols );
  Traits< ::Fabric::EDK::KL::SInt32 >::Destruct( val.rows );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


