#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Quat.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.7.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 7
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:812
#include "global.h"
// Core\Clients\CAPI\KL2EDK.cpp:864
#include "Vec3.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Quat'
// Defined at Mat33.kl:52:1

struct Quat
{
  typedef Quat &Result;
  typedef Quat const &INParam;
  typedef Quat &IOParam;
  typedef Quat &OUTParam;
  
  ::Fabric::EDK::KL::Vec3 v;
  ::Fabric::EDK::KL::Float32 w;
};

inline void Traits<Quat>::ConstructEmpty( Quat &val )
{
  Traits< ::Fabric::EDK::KL::Vec3 >::ConstructEmpty( val.v );
  Traits< ::Fabric::EDK::KL::Float32 >::ConstructEmpty( val.w );
}
inline void Traits<Quat>::ConstructCopy( Quat &lhs, Quat const &rhs )
{
  Traits< ::Fabric::EDK::KL::Vec3 >::ConstructCopy( lhs.v, rhs.v );
  Traits< ::Fabric::EDK::KL::Float32 >::ConstructCopy( lhs.w, rhs.w );
}
inline void Traits<Quat>::AssignCopy( Quat &lhs, Quat const &rhs )
{
  Traits< ::Fabric::EDK::KL::Vec3 >::AssignCopy( lhs.v, rhs.v );
  Traits< ::Fabric::EDK::KL::Float32 >::AssignCopy( lhs.w, rhs.w );
}
inline void Traits<Quat>::Destruct( Quat &val )
{
  Traits< ::Fabric::EDK::KL::Float32 >::Destruct( val.w );
  Traits< ::Fabric::EDK::KL::Vec3 >::Destruct( val.v );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


