#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'RGB.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.7.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 7
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:812
#include "global.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'RGB'
// Defined at RGB.kl:21:1

struct RGB
{
  typedef RGB &Result;
  typedef RGB const &INParam;
  typedef RGB &IOParam;
  typedef RGB &OUTParam;
  
  ::Fabric::EDK::KL::UInt8 r;
  ::Fabric::EDK::KL::UInt8 g;
  ::Fabric::EDK::KL::UInt8 b;
};

inline void Traits<RGB>::ConstructEmpty( RGB &val )
{
  Traits< ::Fabric::EDK::KL::UInt8 >::ConstructEmpty( val.r );
  Traits< ::Fabric::EDK::KL::UInt8 >::ConstructEmpty( val.g );
  Traits< ::Fabric::EDK::KL::UInt8 >::ConstructEmpty( val.b );
}
inline void Traits<RGB>::ConstructCopy( RGB &lhs, RGB const &rhs )
{
  Traits< ::Fabric::EDK::KL::UInt8 >::ConstructCopy( lhs.r, rhs.r );
  Traits< ::Fabric::EDK::KL::UInt8 >::ConstructCopy( lhs.g, rhs.g );
  Traits< ::Fabric::EDK::KL::UInt8 >::ConstructCopy( lhs.b, rhs.b );
}
inline void Traits<RGB>::AssignCopy( RGB &lhs, RGB const &rhs )
{
  Traits< ::Fabric::EDK::KL::UInt8 >::AssignCopy( lhs.r, rhs.r );
  Traits< ::Fabric::EDK::KL::UInt8 >::AssignCopy( lhs.g, rhs.g );
  Traits< ::Fabric::EDK::KL::UInt8 >::AssignCopy( lhs.b, rhs.b );
}
inline void Traits<RGB>::Destruct( RGB &val )
{
  Traits< ::Fabric::EDK::KL::UInt8 >::Destruct( val.b );
  Traits< ::Fabric::EDK::KL::UInt8 >::Destruct( val.g );
  Traits< ::Fabric::EDK::KL::UInt8 >::Destruct( val.r );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


