#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Vec2_i.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.5.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 5
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:803
#include "global.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Vec2_i'
// Defined at Vec2_i.kl:18:1

struct Vec2_i
{
  typedef Vec2_i &Result;
  typedef Vec2_i const &INParam;
  typedef Vec2_i &IOParam;
  typedef Vec2_i &OUTParam;
  
  ::Fabric::EDK::KL::SInt32 x;
  ::Fabric::EDK::KL::SInt32 y;
};

inline void Traits<Vec2_i>::ConstructEmpty( Vec2_i &val )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructEmpty( val.x );
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructEmpty( val.y );
}
inline void Traits<Vec2_i>::ConstructCopy( Vec2_i &lhs, Vec2_i const &rhs )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructCopy( lhs.y, rhs.y );
}
inline void Traits<Vec2_i>::AssignCopy( Vec2_i &lhs, Vec2_i const &rhs )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::AssignCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::SInt32 >::AssignCopy( lhs.y, rhs.y );
}
inline void Traits<Vec2_i>::Destruct( Vec2_i &val )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::Destruct( val.y );
  Traits< ::Fabric::EDK::KL::SInt32 >::Destruct( val.x );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


