#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Vec2_d.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.6.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 6
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:803
#include "global.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Vec2_d'
// Defined at Vec2_d.kl:18:1

struct Vec2_d
{
  typedef Vec2_d &Result;
  typedef Vec2_d const &INParam;
  typedef Vec2_d &IOParam;
  typedef Vec2_d &OUTParam;
  
  ::Fabric::EDK::KL::Float64 x;
  ::Fabric::EDK::KL::Float64 y;
};

inline void Traits<Vec2_d>::ConstructEmpty( Vec2_d &val )
{
  Traits< ::Fabric::EDK::KL::Float64 >::ConstructEmpty( val.x );
  Traits< ::Fabric::EDK::KL::Float64 >::ConstructEmpty( val.y );
}
inline void Traits<Vec2_d>::ConstructCopy( Vec2_d &lhs, Vec2_d const &rhs )
{
  Traits< ::Fabric::EDK::KL::Float64 >::ConstructCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::Float64 >::ConstructCopy( lhs.y, rhs.y );
}
inline void Traits<Vec2_d>::AssignCopy( Vec2_d &lhs, Vec2_d const &rhs )
{
  Traits< ::Fabric::EDK::KL::Float64 >::AssignCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::Float64 >::AssignCopy( lhs.y, rhs.y );
}
inline void Traits<Vec2_d>::Destruct( Vec2_d &val )
{
  Traits< ::Fabric::EDK::KL::Float64 >::Destruct( val.y );
  Traits< ::Fabric::EDK::KL::Float64 >::Destruct( val.x );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


