#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Vec2.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.6.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 6
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:803
#include "global.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Vec2'
// Defined at Vec2.kl:18:1

struct Vec2
{
  typedef Vec2 &Result;
  typedef Vec2 const &INParam;
  typedef Vec2 &IOParam;
  typedef Vec2 &OUTParam;
  
  ::Fabric::EDK::KL::Float32 x;
  ::Fabric::EDK::KL::Float32 y;
};

inline void Traits<Vec2>::ConstructEmpty( Vec2 &val )
{
  Traits< ::Fabric::EDK::KL::Float32 >::ConstructEmpty( val.x );
  Traits< ::Fabric::EDK::KL::Float32 >::ConstructEmpty( val.y );
}
inline void Traits<Vec2>::ConstructCopy( Vec2 &lhs, Vec2 const &rhs )
{
  Traits< ::Fabric::EDK::KL::Float32 >::ConstructCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::Float32 >::ConstructCopy( lhs.y, rhs.y );
}
inline void Traits<Vec2>::AssignCopy( Vec2 &lhs, Vec2 const &rhs )
{
  Traits< ::Fabric::EDK::KL::Float32 >::AssignCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::Float32 >::AssignCopy( lhs.y, rhs.y );
}
inline void Traits<Vec2>::Destruct( Vec2 &val )
{
  Traits< ::Fabric::EDK::KL::Float32 >::Destruct( val.y );
  Traits< ::Fabric::EDK::KL::Float32 >::Destruct( val.x );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


