#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Vec2_c.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.7.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 7
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:812
#include "global.h"
// Core\Clients\CAPI\KL2EDK.cpp:864
#include "Complex.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Vec2_c'
// Defined at Vec2_c.kl:18:1

struct Vec2_c
{
  typedef Vec2_c &Result;
  typedef Vec2_c const &INParam;
  typedef Vec2_c &IOParam;
  typedef Vec2_c &OUTParam;
  
  ::Fabric::EDK::KL::Complex x;
  ::Fabric::EDK::KL::Complex y;
};

inline void Traits<Vec2_c>::ConstructEmpty( Vec2_c &val )
{
  Traits< ::Fabric::EDK::KL::Complex >::ConstructEmpty( val.x );
  Traits< ::Fabric::EDK::KL::Complex >::ConstructEmpty( val.y );
}
inline void Traits<Vec2_c>::ConstructCopy( Vec2_c &lhs, Vec2_c const &rhs )
{
  Traits< ::Fabric::EDK::KL::Complex >::ConstructCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::Complex >::ConstructCopy( lhs.y, rhs.y );
}
inline void Traits<Vec2_c>::AssignCopy( Vec2_c &lhs, Vec2_c const &rhs )
{
  Traits< ::Fabric::EDK::KL::Complex >::AssignCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::Complex >::AssignCopy( lhs.y, rhs.y );
}
inline void Traits<Vec2_c>::Destruct( Vec2_c &val )
{
  Traits< ::Fabric::EDK::KL::Complex >::Destruct( val.y );
  Traits< ::Fabric::EDK::KL::Complex >::Destruct( val.x );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


