#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Vec3_c.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.7.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 7
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:812
#include "global.h"
// Core\Clients\CAPI\KL2EDK.cpp:864
#include "Complex.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Vec3_c'
// Defined at Vec3_c.kl:21:1

struct Vec3_c
{
  typedef Vec3_c &Result;
  typedef Vec3_c const &INParam;
  typedef Vec3_c &IOParam;
  typedef Vec3_c &OUTParam;
  
  ::Fabric::EDK::KL::Complex x;
  ::Fabric::EDK::KL::Complex y;
  ::Fabric::EDK::KL::Complex z;
};

inline void Traits<Vec3_c>::ConstructEmpty( Vec3_c &val )
{
  Traits< ::Fabric::EDK::KL::Complex >::ConstructEmpty( val.x );
  Traits< ::Fabric::EDK::KL::Complex >::ConstructEmpty( val.y );
  Traits< ::Fabric::EDK::KL::Complex >::ConstructEmpty( val.z );
}
inline void Traits<Vec3_c>::ConstructCopy( Vec3_c &lhs, Vec3_c const &rhs )
{
  Traits< ::Fabric::EDK::KL::Complex >::ConstructCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::Complex >::ConstructCopy( lhs.y, rhs.y );
  Traits< ::Fabric::EDK::KL::Complex >::ConstructCopy( lhs.z, rhs.z );
}
inline void Traits<Vec3_c>::AssignCopy( Vec3_c &lhs, Vec3_c const &rhs )
{
  Traits< ::Fabric::EDK::KL::Complex >::AssignCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::Complex >::AssignCopy( lhs.y, rhs.y );
  Traits< ::Fabric::EDK::KL::Complex >::AssignCopy( lhs.z, rhs.z );
}
inline void Traits<Vec3_c>::Destruct( Vec3_c &val )
{
  Traits< ::Fabric::EDK::KL::Complex >::Destruct( val.z );
  Traits< ::Fabric::EDK::KL::Complex >::Destruct( val.y );
  Traits< ::Fabric::EDK::KL::Complex >::Destruct( val.x );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


