#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Vec3_i.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.6.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 6
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:803
#include "global.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Vec3_i'
// Defined at Vec3_i.kl:21:1

struct Vec3_i
{
  typedef Vec3_i &Result;
  typedef Vec3_i const &INParam;
  typedef Vec3_i &IOParam;
  typedef Vec3_i &OUTParam;
  
  ::Fabric::EDK::KL::SInt32 x;
  ::Fabric::EDK::KL::SInt32 y;
  ::Fabric::EDK::KL::SInt32 z;
};

inline void Traits<Vec3_i>::ConstructEmpty( Vec3_i &val )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructEmpty( val.x );
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructEmpty( val.y );
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructEmpty( val.z );
}
inline void Traits<Vec3_i>::ConstructCopy( Vec3_i &lhs, Vec3_i const &rhs )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructCopy( lhs.y, rhs.y );
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructCopy( lhs.z, rhs.z );
}
inline void Traits<Vec3_i>::AssignCopy( Vec3_i &lhs, Vec3_i const &rhs )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::AssignCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::SInt32 >::AssignCopy( lhs.y, rhs.y );
  Traits< ::Fabric::EDK::KL::SInt32 >::AssignCopy( lhs.z, rhs.z );
}
inline void Traits<Vec3_i>::Destruct( Vec3_i &val )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::Destruct( val.z );
  Traits< ::Fabric::EDK::KL::SInt32 >::Destruct( val.y );
  Traits< ::Fabric::EDK::KL::SInt32 >::Destruct( val.x );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


