#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Vec3_cd.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.6.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 6
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:803
#include "global.h"
// Core\Clients\CAPI\KL2EDK.cpp:855
#include "Complex_d.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Vec3_cd'
// Defined at Vec3_cd.kl:21:1

struct Vec3_cd
{
  typedef Vec3_cd &Result;
  typedef Vec3_cd const &INParam;
  typedef Vec3_cd &IOParam;
  typedef Vec3_cd &OUTParam;
  
  ::Fabric::EDK::KL::Complex_d x;
  ::Fabric::EDK::KL::Complex_d y;
  ::Fabric::EDK::KL::Complex_d z;
};

inline void Traits<Vec3_cd>::ConstructEmpty( Vec3_cd &val )
{
  Traits< ::Fabric::EDK::KL::Complex_d >::ConstructEmpty( val.x );
  Traits< ::Fabric::EDK::KL::Complex_d >::ConstructEmpty( val.y );
  Traits< ::Fabric::EDK::KL::Complex_d >::ConstructEmpty( val.z );
}
inline void Traits<Vec3_cd>::ConstructCopy( Vec3_cd &lhs, Vec3_cd const &rhs )
{
  Traits< ::Fabric::EDK::KL::Complex_d >::ConstructCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::Complex_d >::ConstructCopy( lhs.y, rhs.y );
  Traits< ::Fabric::EDK::KL::Complex_d >::ConstructCopy( lhs.z, rhs.z );
}
inline void Traits<Vec3_cd>::AssignCopy( Vec3_cd &lhs, Vec3_cd const &rhs )
{
  Traits< ::Fabric::EDK::KL::Complex_d >::AssignCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::Complex_d >::AssignCopy( lhs.y, rhs.y );
  Traits< ::Fabric::EDK::KL::Complex_d >::AssignCopy( lhs.z, rhs.z );
}
inline void Traits<Vec3_cd>::Destruct( Vec3_cd &val )
{
  Traits< ::Fabric::EDK::KL::Complex_d >::Destruct( val.z );
  Traits< ::Fabric::EDK::KL::Complex_d >::Destruct( val.y );
  Traits< ::Fabric::EDK::KL::Complex_d >::Destruct( val.x );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


