#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Vec4.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.6.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 6
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:803
#include "global.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Vec4'
// Defined at Vec4.kl:19:1

struct Vec4
{
  typedef Vec4 &Result;
  typedef Vec4 const &INParam;
  typedef Vec4 &IOParam;
  typedef Vec4 &OUTParam;
  
  ::Fabric::EDK::KL::Float32 x;
  ::Fabric::EDK::KL::Float32 y;
  ::Fabric::EDK::KL::Float32 z;
  ::Fabric::EDK::KL::Float32 t;
};

inline void Traits<Vec4>::ConstructEmpty( Vec4 &val )
{
  Traits< ::Fabric::EDK::KL::Float32 >::ConstructEmpty( val.x );
  Traits< ::Fabric::EDK::KL::Float32 >::ConstructEmpty( val.y );
  Traits< ::Fabric::EDK::KL::Float32 >::ConstructEmpty( val.z );
  Traits< ::Fabric::EDK::KL::Float32 >::ConstructEmpty( val.t );
}
inline void Traits<Vec4>::ConstructCopy( Vec4 &lhs, Vec4 const &rhs )
{
  Traits< ::Fabric::EDK::KL::Float32 >::ConstructCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::Float32 >::ConstructCopy( lhs.y, rhs.y );
  Traits< ::Fabric::EDK::KL::Float32 >::ConstructCopy( lhs.z, rhs.z );
  Traits< ::Fabric::EDK::KL::Float32 >::ConstructCopy( lhs.t, rhs.t );
}
inline void Traits<Vec4>::AssignCopy( Vec4 &lhs, Vec4 const &rhs )
{
  Traits< ::Fabric::EDK::KL::Float32 >::AssignCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::Float32 >::AssignCopy( lhs.y, rhs.y );
  Traits< ::Fabric::EDK::KL::Float32 >::AssignCopy( lhs.z, rhs.z );
  Traits< ::Fabric::EDK::KL::Float32 >::AssignCopy( lhs.t, rhs.t );
}
inline void Traits<Vec4>::Destruct( Vec4 &val )
{
  Traits< ::Fabric::EDK::KL::Float32 >::Destruct( val.t );
  Traits< ::Fabric::EDK::KL::Float32 >::Destruct( val.z );
  Traits< ::Fabric::EDK::KL::Float32 >::Destruct( val.y );
  Traits< ::Fabric::EDK::KL::Float32 >::Destruct( val.x );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


