#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Vec4_c.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.5.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 5
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:803
#include "global.h"
// Core\Clients\CAPI\KL2EDK.cpp:855
#include "Complex.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Vec4_c'
// Defined at Vec4_c.kl:19:1

struct Vec4_c
{
  typedef Vec4_c &Result;
  typedef Vec4_c const &INParam;
  typedef Vec4_c &IOParam;
  typedef Vec4_c &OUTParam;
  
  ::Fabric::EDK::KL::Complex x;
  ::Fabric::EDK::KL::Complex y;
  ::Fabric::EDK::KL::Complex z;
  ::Fabric::EDK::KL::Complex t;
};

inline void Traits<Vec4_c>::ConstructEmpty( Vec4_c &val )
{
  Traits< ::Fabric::EDK::KL::Complex >::ConstructEmpty( val.x );
  Traits< ::Fabric::EDK::KL::Complex >::ConstructEmpty( val.y );
  Traits< ::Fabric::EDK::KL::Complex >::ConstructEmpty( val.z );
  Traits< ::Fabric::EDK::KL::Complex >::ConstructEmpty( val.t );
}
inline void Traits<Vec4_c>::ConstructCopy( Vec4_c &lhs, Vec4_c const &rhs )
{
  Traits< ::Fabric::EDK::KL::Complex >::ConstructCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::Complex >::ConstructCopy( lhs.y, rhs.y );
  Traits< ::Fabric::EDK::KL::Complex >::ConstructCopy( lhs.z, rhs.z );
  Traits< ::Fabric::EDK::KL::Complex >::ConstructCopy( lhs.t, rhs.t );
}
inline void Traits<Vec4_c>::AssignCopy( Vec4_c &lhs, Vec4_c const &rhs )
{
  Traits< ::Fabric::EDK::KL::Complex >::AssignCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::Complex >::AssignCopy( lhs.y, rhs.y );
  Traits< ::Fabric::EDK::KL::Complex >::AssignCopy( lhs.z, rhs.z );
  Traits< ::Fabric::EDK::KL::Complex >::AssignCopy( lhs.t, rhs.t );
}
inline void Traits<Vec4_c>::Destruct( Vec4_c &val )
{
  Traits< ::Fabric::EDK::KL::Complex >::Destruct( val.t );
  Traits< ::Fabric::EDK::KL::Complex >::Destruct( val.z );
  Traits< ::Fabric::EDK::KL::Complex >::Destruct( val.y );
  Traits< ::Fabric::EDK::KL::Complex >::Destruct( val.x );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


