#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Vec4_d.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.6.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 6
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:803
#include "global.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Vec4_d'
// Defined at Vec4_d.kl:19:1

struct Vec4_d
{
  typedef Vec4_d &Result;
  typedef Vec4_d const &INParam;
  typedef Vec4_d &IOParam;
  typedef Vec4_d &OUTParam;
  
  ::Fabric::EDK::KL::Float64 x;
  ::Fabric::EDK::KL::Float64 y;
  ::Fabric::EDK::KL::Float64 z;
  ::Fabric::EDK::KL::Float64 t;
};

inline void Traits<Vec4_d>::ConstructEmpty( Vec4_d &val )
{
  Traits< ::Fabric::EDK::KL::Float64 >::ConstructEmpty( val.x );
  Traits< ::Fabric::EDK::KL::Float64 >::ConstructEmpty( val.y );
  Traits< ::Fabric::EDK::KL::Float64 >::ConstructEmpty( val.z );
  Traits< ::Fabric::EDK::KL::Float64 >::ConstructEmpty( val.t );
}
inline void Traits<Vec4_d>::ConstructCopy( Vec4_d &lhs, Vec4_d const &rhs )
{
  Traits< ::Fabric::EDK::KL::Float64 >::ConstructCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::Float64 >::ConstructCopy( lhs.y, rhs.y );
  Traits< ::Fabric::EDK::KL::Float64 >::ConstructCopy( lhs.z, rhs.z );
  Traits< ::Fabric::EDK::KL::Float64 >::ConstructCopy( lhs.t, rhs.t );
}
inline void Traits<Vec4_d>::AssignCopy( Vec4_d &lhs, Vec4_d const &rhs )
{
  Traits< ::Fabric::EDK::KL::Float64 >::AssignCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::Float64 >::AssignCopy( lhs.y, rhs.y );
  Traits< ::Fabric::EDK::KL::Float64 >::AssignCopy( lhs.z, rhs.z );
  Traits< ::Fabric::EDK::KL::Float64 >::AssignCopy( lhs.t, rhs.t );
}
inline void Traits<Vec4_d>::Destruct( Vec4_d &val )
{
  Traits< ::Fabric::EDK::KL::Float64 >::Destruct( val.t );
  Traits< ::Fabric::EDK::KL::Float64 >::Destruct( val.z );
  Traits< ::Fabric::EDK::KL::Float64 >::Destruct( val.y );
  Traits< ::Fabric::EDK::KL::Float64 >::Destruct( val.x );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


