#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Vec4_i.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.5.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 5
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:803
#include "global.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Vec4_i'
// Defined at Vec4_i.kl:19:1

struct Vec4_i
{
  typedef Vec4_i &Result;
  typedef Vec4_i const &INParam;
  typedef Vec4_i &IOParam;
  typedef Vec4_i &OUTParam;
  
  ::Fabric::EDK::KL::SInt32 x;
  ::Fabric::EDK::KL::SInt32 y;
  ::Fabric::EDK::KL::SInt32 z;
  ::Fabric::EDK::KL::SInt32 t;
};

inline void Traits<Vec4_i>::ConstructEmpty( Vec4_i &val )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructEmpty( val.x );
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructEmpty( val.y );
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructEmpty( val.z );
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructEmpty( val.t );
}
inline void Traits<Vec4_i>::ConstructCopy( Vec4_i &lhs, Vec4_i const &rhs )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructCopy( lhs.y, rhs.y );
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructCopy( lhs.z, rhs.z );
  Traits< ::Fabric::EDK::KL::SInt32 >::ConstructCopy( lhs.t, rhs.t );
}
inline void Traits<Vec4_i>::AssignCopy( Vec4_i &lhs, Vec4_i const &rhs )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::AssignCopy( lhs.x, rhs.x );
  Traits< ::Fabric::EDK::KL::SInt32 >::AssignCopy( lhs.y, rhs.y );
  Traits< ::Fabric::EDK::KL::SInt32 >::AssignCopy( lhs.z, rhs.z );
  Traits< ::Fabric::EDK::KL::SInt32 >::AssignCopy( lhs.t, rhs.t );
}
inline void Traits<Vec4_i>::Destruct( Vec4_i &val )
{
  Traits< ::Fabric::EDK::KL::SInt32 >::Destruct( val.t );
  Traits< ::Fabric::EDK::KL::SInt32 >::Destruct( val.z );
  Traits< ::Fabric::EDK::KL::SInt32 >::Destruct( val.y );
  Traits< ::Fabric::EDK::KL::SInt32 >::Destruct( val.x );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


