#pragma once

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Vec_d.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.6.0
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 6
# error "This file needs to be rebuilt for the current EDK version!"
#endif

// Core\Clients\CAPI\KL2EDK.cpp:803
#include "global.h"

namespace Fabric {
namespace EDK {
namespace KL {


// KL struct 'Vec_d'
// Defined at Vec_d.kl:19:1

struct Vec_d
{
  typedef Vec_d &Result;
  typedef Vec_d const &INParam;
  typedef Vec_d &IOParam;
  typedef Vec_d &OUTParam;
  
  ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::Float64 > vals;
};

inline void Traits<Vec_d>::ConstructEmpty( Vec_d &val )
{
  Traits< ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::Float64 > >::ConstructEmpty( val.vals );
}
inline void Traits<Vec_d>::ConstructCopy( Vec_d &lhs, Vec_d const &rhs )
{
  Traits< ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::Float64 > >::ConstructCopy( lhs.vals, rhs.vals );
}
inline void Traits<Vec_d>::AssignCopy( Vec_d &lhs, Vec_d const &rhs )
{
  Traits< ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::Float64 > >::AssignCopy( lhs.vals, rhs.vals );
}
inline void Traits<Vec_d>::Destruct( Vec_d &val )
{
  Traits< ::Fabric::EDK::KL::VariableArray< ::Fabric::EDK::KL::Float64 > >::Destruct( val.vals );
}
} // namespace KL
} // namespace EDK
} // namespace Fabric


